### ISSUE TITLE
Runtime panic: When an asset is finalized before an investor list is assembled

### ISSUE THREAD

**Issue by ilhanu** [Fair-Squares/fair-squares#225]
**Description**

_The runtime panics when an asset get's finalised before a investors list is assembled --> event `InvestorListCreationSuccessful`_

**Steps to Reproduce**

1. Onboard an asset
2. Finalize the asset with the finalizer-pallet  before the bidding pallet can assemble a succesful list of investors
3. In the change of the epoch the runtime will panic. 

**Expected  Behavior**

_The runtime panic should not be allowed to happen, when the notary finalizes an asset that has not seen the event `InvestorListCreationSuccessful`, it should report an error and not continue the finalisation process.

Currently we are only looking for if the status is `onboarded`, but we need to add another state to it for not allowing this to happen_

**Logs, Errors or Screenshots**

**[Additional Information**](https://paste.ubuntu.com/p/KfwkC9mZZs/)

**Comment by ndkazu** [comment]
*I think I found out the origin of the problem:*
- In the current runtime settings, manual execution of the extrinsic `force_process_onboarded_asset` will consistently clash with the execution of the same extrinsic triggered by the hook in pallet_bidding. Why?
⇒ the execution of this extrinsic is actually time-consuming, especially the investor list creation part. The asset's status is changed only after a successful investor list creation: if the hook triggers the `process_onboarded_asset` before the end of the list creation, it will find `fake onboarded because already being processed` assets, and start the same job a 2nd time on the same assets.
- The simplest way to correct this is to considerably increase the time between checks of the chain by the bidding pallet. 
- We could also question the necessity of allowing the manual trigger of this process.

**Comment by ilhanu** [comment]
I was not able to produce the it with several assets again. Afaik I didn't use the `force_process_onboarded_asset` call.
The manual triggers were temporary created for testing purposes.
