### ISSUE TITLE
Milestone 2 issues definition

### ISSUE THREAD

**Issue by letodunc** [Fair-Squares/fair-squares#94]
For the milestone 2, 2 new pallets will be added to the project: onboarding and voting. There are existing pallets implementing what it is expected to do with these new pallets.
We need to define the list of expected features. The objective is to list the functionalities of the pallets and to see if a customization of the existing pallets is necessary. We need to clarify some points before creating the issue for differents developments.

The brainstorming can be base on the following documents:
https://github.com/Fair-Squares/Grants-Program/blob/master/applications/fair_squares.md
https://cdn.discordapp.com/attachments/945301940710023178/996329719979069501/866EB590-66C7-44FB-ADD0-765ADA9B15A9.jpg

A first draft of the methods (names used for the example, may change) could be the following:

 **onboarding**
 + register => register a house
   x what input informations are needed ?
   x for the beginning the submission will be approved with basic controls to be defined
 + mint => create a NFT for a house
   x what information is needed as input ?
   x how a house is represented ? 
   x to which fund is the deposit fee addressed? Should the pallet housing fund also manage the fees
+ destroyNFT => destroy a nft

**voting**
 + createProposal => create a sales proposal associated with a house
   x fee depsit?
 + updateProposal => modify a proposal
   x what are the implications? Additional fees?
 + voteProposal => add a vote to a proposal
   x can be split into 2 functions for the housing council and investors (voteProposalInvestor and voteProposalCouncil) or one function that distinguishes between the two

**housing_fund**

- With the deposit fee and slash deposit, a change can be made into housing_fund to implement them so the fund management is done by one pallet.

This is a proposition to have a base of discussion. Be free to add something I missed. Let's be like Pain in Naruto, multiple eyes give us more possibilities :)

**Comment by ndkazu** [comment]
Nice first draft, I wil reflect on it, and share my findings during the technical meeting.

**Comment by ilhanu** [comment]
### **onboardmodule:**


- call::onboardAsset
  - _mandatory_: User needs to have a sellerRole 
  - price
  - squareMeters / m²
  - bond/depsitFee (from treasury-pallet) // User cannot define this, set in runtime
  -  metadata / proofs
  --> triggers [mint_Asset](https://github.com/rmrk-team/rmrk-substrate/blob/main/pallets/rmrk-core/src/lib.rs#L341-L414)
> **notes:**
> 1. the users funds are reserved in it's account, as long as the asset is minted and not sold or cancelled the bond stays reserved. 
> 2. The nft should have an AccountId that can be the treasury of the house
> 3. The house just has an assetId/nftId
> 4. The asset should have a status, onboarding(when being voted on), onboarded (when finalized), delisted ( nft burned and asset delisted) 

- call::cancelAssetOnboarding
  - _mandatory_: User needs to have a sellerRole 
  - _mandatory_: User needs to be the seller that called or this is a sudo-call/ housing-council
  --> triggers [burn](https://github.com/paritytech/substrate/blob/master/frame/uniques/src/lib.rs#L546-L564)
> **notes:**
> 1. the users funds that were reserved are released to the sellers account, if easy to implement we can get 10% of the bond go to the treasury not the housing-fund

getter::showAsset(assetId) --> price, sqm, seller, status
getter::showNextAssetId ( [counter](https://github.com/rmrk-team/rmrk-substrate/blob/main/pallets/rmrk-core/src/lib.rs#L93-L95)) 

> **notes:**
> 1. uniques-pallet has ItemId and collectionId these are for us assetId and assetType. 

______

**Comment by ndkazu** [comment]
**voting-pallet**

This pallet will implement 2 kinds of voting system:

**Concil vote:**
The concil voting system will be based on the Collective-pallet: 
- The council is composed of a defined number of "Servicers" role accounts in charge of screening submitted proposals.
- A "prime" member may be set to help determine the default vote behavior based on chain config.

call::submit_proposal
A Seller role submit a proposal
- As input parameters, the accountId of a SELLER (role), and a proposal index which should be linked to a struct containing information about the [asset/asset_nft] are used. Proposal index is monitored by the OnBoard_Module. 
- The proposal index is transmited to the treasury-pallet, in order to trigger a spending_proposal, and lock a deposit fee proportional to the value of the proposal.
The proposal index is finally stored in a waiting list, waiting to be selected by council members for examination.

call::council_vote
A council member submit a proposal index for examination by the council followed by a voting session.
- In case of unfavorable vote result, the negative vote answer is transmited to the treasury's spending_proposal, which in turn will trigger the transfer of the deposit fee to the treasury.
- In case of favorable vote, a Referendum (Democracy_pallet) linked to this proposal is immediately triggered, waiting for Investor's vote.

**Investors vote**
This vote is managed by the democracy-pallet

call::propose
- Add proposal to democracy-pallet voting queue. this part requires the proposal_hash as an input (see example in https://github.com/Fair-Squares/fair-squares/blob/structure_template/pallets/template/src/roles/mod.rs  from line 191)

call::start_referendum
- see example in https://github.com/Fair-Squares/fair-squares/blob/structure_template/pallets/template/src/roles/mod.rs  from line 196
- In case of unfavorable vote result, the negative vote answer is transmited to the treasury's spending_proposal, which in turn will trigger the transfer of the deposit fee to the treasury.
